version: '3.8'

services:
  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    container_name: knowledge-nexus-gradio
    ports:
      - "7860:7860"  # Map host port 7860 to container port 7860 (Gradio default)
    volumes:
      - .:/app # Mount the current directory into the container for live code changes (optional)
      - knowledge_nexus_files_volume:/app/knowledge_nexus_files # Persist uploaded/generated files
    env_file:
      - .env # Load environment variables from .env file
    environment:
      # Ensure Neo4j connection details point to the service container
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USERNAME: "neo4j"
      # NEO4J_PASSWORD is read from .env file
      # Add any other necessary environment variables here
      # OPENAI_API_KEY: ${OPENAI_API_KEY} # Also read from .env
    depends_on:
      - neo4j
    restart: unless-stopped

  neo4j:
    image: neo4j:latest # You might want to pin this to a specific version, e.g., neo4j:5.18
    container_name: knowledge-nexus-neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins # Volume for APOC plugins if needed
      # - ./plugins:/plugins # Mount local plugins directory if you have custom ones
    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD}" # Use the password from the .env file
      # Enable APOC Core procedures (often useful)
      NEO4J_PLUGINS: '["apoc"]'
      # Adjust memory settings if needed
      # NEO4J_server_memory_pagecache_size: "1G"
      # NEO4J_server_memory_heap_initial__size: "1G"
      # NEO4J_server_memory_heap_max__size: "1G"
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_plugins:
  knowledge_nexus_files_volume: 